### PR TITLE
Add standalone Dockerfile and update Alpine build documentation

### PR DESCRIPTION
**Pull request by T31M**
Hope this is helpful to some :) 

Open for any suggestions / improvements / notes 👍🏻

### CODE REVIEW

**Comment by T31M** [comment]
Have been informed of hard requirement to use zstd version 1.4.4 and nothing else. Will try to incorporate or close the PR otherwise 👍🏻

**Comment by T31M** [comment]
Will be Updated to just include build steps for Alpine & remove Alpine Dockerfile adaptions.

**Comment by Arkiver2** [comment]
Thank you @T31M! Can you please PR the build steps in the README to https://github.com/ArchiveTeam/standalone-readme-template/blob/master/README.wget-at.md ?

They will then be included in new projects moving forward.

**Comment by T31M** [comment]
Great suggestion, didn't know this existed. Thanks ! Here you go: https://github.com/ArchiveTeam/standalone-readme-template/pull/11

**Comment by Arkiver2** [comment]
Your PR https://github.com/ArchiveTeam/standalone-readme-template/pull/11 has been merged. Considering this closed now.

We do have to move to Lua 5.4 and Zstd 1.5.1, and this will happen at some point in the future.

**Pull request closed without merging**
